apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: sensors
    user: telegraf-username
    password: telegraf-password
    url: http://localhost:8086
    jsonData:
      httpMode: GET
